steps:

# Build the new docker image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/laravel_docker_compose', '.']

# Run the app and dependencies in the background using docker-compose.
# Warning: this won't be cleaned up, which might be an issue if you run it
# with the local builder.
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:v1', 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}']
  images: ['gcr.io/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}']
