steps:

# Build the new docker image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/laravel_docker_compose@sha256:318129b6bd3320ff809218b90088ffe3093991c82e108abe1e5808b73369ce4d', '.']

  # Run the app and dependencies in the background using docker-compose.
# Warning: this won't be cleaned up, which might be an issue if you run it
# with the local builder.
- name: 'docker/compose:2.3'
  args: ['up', '-d']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
