version: '2.3'

services:
  app:
    image: gcr.io/${PROJECT_ID}/laravel_docker_compose@sha256:318129b6bd3320ff809218b90088ffe3093991c82e108abe1e5808b73369ce4d
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=app
      - NGINX_PORT=80
    volumes:
      - .:/var/www
    networks:
      - app-network

  db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", 'mysql -uroot --database=laravel --password=root --execute="select count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 2s
      timeout: 2s
      retries: 7

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
