apiVersion: v1
kind: ConfigMap
metadata:
  name: app-conf
data:
  env: |
   APP_NAME=docker_laravel
   APP_ENV=local
   APP_KEY=base64:bO1gmI6Rjjkobu5BXn+pmKRlmF/QVWJPnC3lQzzCqSc=
   APP_DEBUG=true
   APP_URL=http://localhost
   LOG_CHANNEL=stach

   DB_CONNECTION=mysql
   DB_HOST=mysql-server
   DB_PORT=3306
   DB_DATABASE=laravel
   DB_USERNAME=root

   BROADCAST_DRIVER=log
   CACHE_DRIVER=file
   QUEUE_CONNECTION=sync
   SESSION_DRIVER=file
   SESSION_LIFETIME=120

   REDIS_HOST=redis-service
   REDIS_PASSWORD=null
   REDIS_PORT=6379
